aur-get now shows diff from old version after dowloading

diff --git a/aur-helperfunctions b/aur-helperfunctions
--- a/aur-helperfunctions
+++ b/aur-helperfunctions
@@ -13,7 +13,16 @@ aur-get () {
 	[[ -d "$PKGBUILDIR/$1" ]] && { rm -rf "$PKGBUILDIR/$1-prev"; mv "$PKGBUILDIR/$1" "$PKGBUILDIR/$1-prev"; }
 	[[ -e "$1.tar.gz" ]] && { rm -f "$1-prev.tar.gz"; mv "$1.tar.gz" "$1-prev.tar.gz"; }
 	if wget -q "https://aur.archlinux.org/packages/${1:0:2}/$1/$1.tar.gz"; then
-		cd "$PKGBUILDIR" && tar xf "$SRCDIR/$1.tar.gz" && cd "$1"
+		cd "$PKGBUILDIR" && tar xf "$SRCDIR/$1.tar.gz" &&\
+		cd "$1" && {
+			if [[ -d ../"$1"-prev/ ]]; then
+				local COLN="\033[0m" COLE="\033[1;39m"
+				echo -e "${COLE}diff from old version:${COLN}"
+				diff -r . ../"$1"-prev/
+				echo -e "${COLE}end diff${COLN}"
+			fi
+			true
+		}
 	else
 		false
 	fi
@@ -210,6 +219,43 @@ aur-check () {
 			echo -e "${COLG}None to update${COLN}"
 	IFS="$OLDIFS"
 	(($return&${#listtoupdate[@]}==0))
+}
+
+aur-sobump-pre () {
+	#+ checks missing dynamic libraries
+
+	local pkg i provided linked linkedraw found LINKER
+	local -a packages=()
+
+	if (($#>0)); then
+		provided=$( pacman -Qql "$@" )
+	fi
+	if ((${#provided}==0)); then
+		echo "input error" >&2 
+		return 1
+	fi
+	
+	#packages=( $( aur-local-packages | cut -f 1 -d " " | ( IFS=$'\n'; grep -v -F "$*" ) )  )
+	while read pkg; do
+		packages+=( $( LANG=C pacman -Qi $pkg | grep 'Requires' | cut -f 2 -d ':' | grep -v '^None$' ) )
+	done < <( aur-local-packages | cut -f 1 -d " " )
+
+	for pkg in "${packages[@]}"; do
+		linkedraw=$(
+			for i in $( pacman -Qql $pkg ); do
+				for LINKER in /lib/ld-linux-x86-64.so.2 /lib/ld-linux.so.2; do
+					if $LINKER --verify "$i" >/dev/null ; then
+						$LINKER --list "$i"
+					fi
+				done
+			done
+		)
+ 		linked=$( sed -n -e 's:.*=>[^/]*\(/.*\) (0x.*:\1:p' <<<"$linkedraw" )
+		found=$( comm -12 <( sort -u <<<"$linked" ) <( sort -u <<<"$provided" ) )
+		if ((${#found}>0)); then
+			echo -e "$pkg needs:\n$found\n\n"
+		fi
+	done
 }
 
 aur-sobump () {
